DEBUG:cave.cavefacade.CAVE:Running CAVE version 1.1.3
INFO:cave.cavefacade.CAVE:Saving results to 'bohb/test/'
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Detected and loaded "bohb/transfer_config/KMNIST_2_2_20_K49/configspace.json". No backup-cs necessary
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:Loading configuration failed... trying alternatives
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cave/utils/hpbandster2smac.py", line 122, in hpbandster2smac
    config = self._get_config(run.config_id, id2config_mapping, cs)
  File "/usr/local/lib/python3.6/dist-packages/cave/utils/hpbandster2smac.py", line 87, in _get_config
    config = Configuration(cs, id2config[config_id]['config'])
  File "ConfigSpace/configuration_space.py", line 1010, in ConfigSpace.configuration_space.Configuration.__init__
ValueError: Trying to set illegal value '14' (type '<class 'int'>') for hyperparameter 'channel_1, Type: UniformInteger, Range: [3, 12], Default: 3' (default-value has type '<class 'int'>').
DEBUG:cave.utils.hpbandster2smac.HpBandSter2SMAC:None of the alternatives worked...
